name: RustAction

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt_build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fmt
      run: cargo fmt -- --check
    - name: install
      uses: actions-rs/install@v0.1
      with:
        crate: wasm-pack
        version: latest
        use-tool-cache: true
    - name: Build
      run: wasm-pack build --target web
    - name: Run tests
      run: cargo test
